// Generated by CoffeeScript 1.3.3
(function() {
  var camera, control, light, mesh, renderer, scene, textGeo, textMaterialFront, textMaterialSide;

  scene = new THREE.Scene();

  textGeo = new THREE.TextGeometry('Hello World!', {
    size: 70,
    height: 20,
    curveSegments: 4,
    font: "optimer",
    weight: "bold",
    style: "normal",
    material: 0,
    extrudeMaterial: 1
  });

  textMaterialFront = new THREE.MeshBasicMaterial({
    color: 0x66ff66,
    opacity: 1
  });

  textMaterialSide = new THREE.MeshBasicMaterial({
    color: 0x00aa00
  });

  textGeo.materials = [textMaterialFront, textMaterialSide];

  mesh = new THREE.Mesh(textGeo, new THREE.MeshFaceMaterial());

  mesh.position = {
    x: 0,
    y: 0,
    z: 0
  };

  mesh.rotation.x = 0;

  mesh.rotation.y = Math.PI * 2;

  scene.add(mesh);

  camera = new THREE.PerspectiveCamera(40, document.width / document.height, 1, 10000);

  camera.position.y = 300;

  camera.position.z = 1000;

  renderer = new THREE.WebGLRenderer({
    antialias: true
  });

  renderer.setSize(document.width, document.height);

  document.body.appendChild(renderer.domElement);

  light = new THREE.DirectionalLight(0xFFFFFF);

  light.position = {
    x: 100,
    y: 1000,
    z: 1000
  };

  scene.add(light);

  control = new THREE.TrackballControls(camera, renderer.domElement);

  setInterval(function() {
    control.update();
    return renderer.render(scene, camera);
  }, 100);

}).call(this);
